export const TYPES = {
  ADD_TO_CART: 'ADD_TO_CART',
  ADD_ONE_FROM_CART: 'ADD_ONE_FROM_CART',
  REMOVE_ONE_FROM_CART: 'REMOVE_ONE_FROM_CART',
  REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
  RESET_CART: 'RESET_CART',
  SET_CONTENT_VIEWED: 'SET_CONTENT_VIEWED',
};
